name: 'Sync Deploy Branches with Main'
description: 'Discovers all deploy/* branches and syncs them with main by force-pushing main to each deploy branch'
author: 'PionCorp'
branding:
  icon: 'git-branch'
  color: 'blue'

inputs:
  exclude-branches:
    description: 'Comma-separated list of deploy branches to exclude from syncing'
    required: false
    default: 'deploy/example,deploy/dummy'
  token:
    description: 'GitHub token with write permissions for repository access (required for git push operations)'
    required: true

outputs:
  branches-synced:
    description: 'JSON array of branches that were synced'
    value: ${{ steps.sync.outputs.branches-synced }}
  branches-discovered:
    description: 'JSON array of all deploy branches discovered'
    value: ${{ steps.sync.outputs.branches-discovered }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Install tools (jq)
      shell: bash
      run: |
        set -e
        
        # jq 설치 (없을 경우에만)
        if ! command -v jq >/dev/null 2>&1; then
          apt-get update -y
          apt-get install -y jq
        fi

    - name: Setup git authentication
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # Setup authentication for git push
        echo "https://github-actions[bot]:${{ inputs.token }}@github.com" > ~/.git-credentials
        git config --global credential.helper store

    - name: Discover and sync deploy branches
      id: sync
      shell: bash
      run: |
        set -euo pipefail
        
        # Get deploy branches
        mapfile -t BRANCHES < <(
          git ls-remote --heads origin 'refs/heads/deploy/*' \
          | awk '{print $2}' \
          | sed 's#^refs/heads/##'
        )
        
        # Filter excluded branches
        IFS=',' read -r -a EXCLUDES <<< "${{ inputs.exclude-branches }}"
        filtered=()
        for b in "${BRANCHES[@]}"; do
          skip=false
          for ex in "${EXCLUDES[@]}"; do
            [[ -n "$ex" && "$b" == "$ex" ]] && skip=true && break
          done
          $skip || filtered+=("$b")
        done
        
        # Output discovered branches
        printf '%s\n' "${filtered[@]}" | jq -R . | jq -c -s . > discovered.json
        echo "branches-discovered=$(cat discovered.json)" >> "$GITHUB_OUTPUT"
        
        if [[ ${#filtered[@]} -eq 0 ]]; then
          echo "No deploy branches found to sync"
          echo "branches-synced=[]" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        
        # Sync each branch by force-pushing main to it
        synced=()
        for branch in "${filtered[@]}"; do
          git push origin "origin/main:refs/heads/${branch}" --force
          echo "Synced branch ${branch} with main"
          synced+=("$branch")
        done
        
        # Output synced branches
        printf '%s\n' "${synced[@]}" | jq -R . | jq -c -s . > synced.json
        echo "branches-synced=$(cat synced.json)" >> "$GITHUB_OUTPUT"
